In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.3.1


在TensorFlow中，tensor是一个类，也是存储和变换数据的主要工具。如果你之前用过NumPy，你会发现tensor和NumPy的多维数组非常类似。然而，tensor提供GPU计算和自动求梯度等更多功能，这些使tensor更加适合深度学习。

### 2.2.1 创建 tensor

x = tf.constant(range(12))

In [4]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [5]:
len(x)

12

In [10]:
x.shape

TensorShape([12])

In [13]:
x.numpy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [14]:
x = tf.reshape(x,(3,4))

In [15]:
x.numpy()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [16]:
x = tf.reshape(x,(-1,4))

In [17]:
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [19]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [20]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

也可以通过Python的列表（list）指定需要创建的tensor中每个元素的值。

In [21]:
Y = tf.constant([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

In [22]:
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

随机生成tensor中每个元素的值。下面我们创建一个形状为(3, 4)的tensor。它的每个元素都随机采样于均值为0、标准差为1的正态分布。m

In [23]:
z = tf.random.normal(shape=(3,4),mean=0,stddev=1)

In [24]:
z

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.9470756 , -1.1618366 , -0.6685635 , -1.5053873 ],
       [ 1.7113779 ,  0.74551165,  0.76067084, -0.14544576],
       [-0.8079664 , -0.4134355 , -1.223442  , -0.17049004]],
      dtype=float32)>

###  2.2 运算

In [25]:
x + Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]], dtype=int32)>

按元素乘法：

In [26]:
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [27]:
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

In [28]:
x * Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

按元素做指数运算：

In [29]:
Y = tf.cast(Y, tf.float32)

In [30]:
Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]], dtype=float32)>

In [31]:
tf.exp(Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.59815  , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

矩阵乘法

In [37]:
Y = tf.cast(Y, tf.int32)

In [38]:
tf.matmul(x, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]], dtype=int32)>

####  将多个tensor连结（concatenate
下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，即形状中左起第二个元素）连结两个矩阵。可以看到，输出的第一个tensor在维度0的长度（ 6 ）为两个输入矩阵在维度0的长度之和（ 3+3 ），而输出的第二个tensor在维度1的长度（ 8 ）为两个输入矩阵在维度1的长度之和（ 4+4 ）。

In [40]:
tf.concat([x,Y],axis=0)

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]], dtype=int32)>

In [41]:
tf.concat([x,Y],axis=1)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]], dtype=int32)>

条件判断式

In [42]:
tf.equal(x,Y)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

tensor中的所有元素求和得到只有一个元素的tensor

In [43]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [44]:
x = tf.cast(x, tf.float32)

范数

In [45]:
tf.norm(x)

<tf.Tensor: shape=(), dtype=float32, numpy=22.494444>

### 2.2.3 广播机制

当对两个形状不同的tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个tensor形状相同后再按元素运算。
- matmul 不能触发广播机制

In [46]:
A = tf.reshape(tf.constant(range(3)), (3,1))
B = tf.reshape(tf.constant(range(2)), (1,2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

由于A和B分别是3行1列和1行2列的矩阵，如果要计算A + B，那么A中第一列的3个元素被广播（复制）到了第二列，而B中第一行的2个元素被广播（复制）到了第二行和第三行。如此，就可以对2个3行2列的矩阵按元素相加。

In [47]:
A + B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

2.2.4 索引

In [57]:
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

利用索引可以直接截取tensor,左闭右开原则。

In [58]:
x[1:3]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

通过Variable()构造函数后，此variable的类型和形状固定不能修改了，但值可以用assign方法修改,通过Variable()生成的variables就是一个tensor，可以作为graph中其他op的输入。

可以指定tensor中需要访问的单个元素的位置，如矩阵中行和列的索引，并为该元素重新赋值。

In [59]:
x = tf.Variable(x)
x[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

也可以截取一部分元素，并为它们重新赋值

In [64]:
x = tf.Variable(x)
x[1:2,:].assign(tf.ones(x[1:2,:].shape, dtype = tf.int32)*12)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]], dtype=int32)>

2.2.5 运算的内存开销

前面的例子里我们对每个操作新开内存来存储运算结果。举个例子，即使像Y = X + Y这样的运算，我们也会新开内存，然后将Y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [65]:
x = tf.Variable(x)

In [69]:
before = id(Y)
Y = Y + x
id(Y) == before

False

如果想指定结果到特定内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们先通过zeros_like创建和Y形状相同且元素为0的tensor，记为Z。接下来，我们把X + Y的结果通过assign 和[:] 写进Z对应的内存中。

In [75]:
z = tf.Variable(tf.zeros_like(Y))
before = id(z)
z[:].assign = x + Y
id(z) == before

True

实际上，上例中我们还是为X + Y开了临时内存来存储计算结果，再复制到Z对应的内存。如果想避免这个临时内存开销，我们可以使用assign_{运算符全名}函数。

In [79]:
Z = tf.add(x, Y)
id(Z) == before

False

如果X的值在之后的程序中不会复用，我们也可以用 X[:] = X + Y 或者 X += Y 来减少运算的内存开销。

In [83]:
before = id(x)
x.assign_add(Y)
id(x) == before

True

### 2.2.6 tensor 和 NumPy 相互变换

虽然TensorFlow网络在输入Numpy数据时会自动转换为Tensor来处理，但是我们自己也可以去显式的转换：

#### Tensor2Numpy

In [85]:
data_numpy = x.numpy()

In [86]:
data_numpy

array([[ 4,  5, 14, 15],
       [38, 40, 42, 44],
       [32, 33, 34, 35]], dtype=int32)

#### Numpy2Tensor

In [87]:
data_tensor= tf.convert_to_tensor(data_numpy)

In [88]:
data_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 4,  5, 14, 15],
       [38, 40, 42, 44],
       [32, 33, 34, 35]], dtype=int32)>