In [1]:
import tensorflow as tf

### 2.1 自动求梯度
- 在深度学习中，我们经常需要对函数求梯度（gradient）。本节将介绍如何使用tensorflow2.0提供的GradientTape来自动求梯度。

2.3.1 简单示例  y = 2 * x * x 求梯度

In [12]:
x = tf.reshape(tf.Variable(range(4),dtype=tf.float32),(4,1))
with tf.GradientTape() as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x),x) # 28
dy_dx = t.gradient(y,x)
dy_dx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]], dtype=float32)>

GradientTape也可以嵌套多层用来计算高阶导数

In [14]:
x = tf.reshape(tf.Variable(range(4),dtype=tf.float32),(4,1))
with tf.GradientTape() as t:
    t.watch(x)
    with tf.GradientTape() as tt:
        tt.watch(x)
        y = 2 * tf.matmul(tf.transpose(x),x) # 28
    dy_dx = tt.gradient(y,x)
dy2_dx2 = t.gradient(dy_dx,x)
print(dy_dx,dy2_dx2)

tf.Tensor(
[[ 0.]
 [ 4.]
 [ 8.]
 [12.]], shape=(4, 1), dtype=float32) tf.Tensor(
[[4.]
 [4.]
 [4.]
 [4.]], shape=(4, 1), dtype=float32)


另外，默认情况下GradientTape的资源在调用gradient函数后就被释放，再次调用就无法计算了。所以如果需要多次计算梯度，需要开启persistent=True属性，

In [16]:
x = tf.reshape(tf.Variable(range(4),dtype=tf.float32),(4,1))
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x),x) # 28
    z = 2 * y
dz_dx = t.gradient(z,x)
dy_dx = t.gradient(y,x)
print(dy_dx,dz_dx)
del t  # 删除这个上下文胶带

tf.Tensor(
[[ 0.]
 [ 4.]
 [ 8.]
 [12.]], shape=(4, 1), dtype=float32) tf.Tensor(
[[ 0.]
 [ 8.]
 [16.]
 [24.]], shape=(4, 1), dtype=float32)
